language: java
env:
  global:
    - # ^^ OSSRH_USERNAME
    - secure: "Tk+ivlTRsIOQRs2dnGQOPYR5ODjhAj4lNCJu8rpuElYiHdsgSIUyhOv42NsmxLkxYR5PP55c4K4XZieuI6bLR+tlwORsjoE/VUxWs0F+ugPH37m9NcpbEWD7y83Z5FDoh4jxInc21bQolOQID+2BBEUPa1OW+IeTqGZPJkDXWnNCY5xFF8QfmZymECS8bCDqaWfF7tpaV1lA9z13GslR47RfgAd6HOq/j31LpSgCwLVVSkxkCqjCKJU7AsJeWh4kTgmKaUXeHhDLn0FirN5dGHldPYZ+/PM+k0nIWNU1W0VIFsDAvl24ppVXgvImmzlk11n7U2Wa8IfU1oPNnQrT82JR6j8GpKPdEZjpyaoyJy9Umt0rQiqB2xhFxtfVAiCiM4Bb44eK4jilfNBKSMYaJ02DfDixpaPnI9+dlGN1fz9VY5geHiYZAJN8wBrL/3jLRJ6yBuo9GDLaR5jtA6G1mg351uKyVI4ICE0vADUYnOMLBfZLaZUlGqJrBXwN5KXuKhGcMQeKr/dMXjjnlY+FdDnjZTTqA7zzfx8RF7v57B2FIdGszGSxYmu73IvokP3gwcxdSAzdXdf9JJnzacJ492c3G8OhLwqSDTOLnetfI3gSVMRHpDmvYttS3DMk9je0Du+miY9KXwUNyRT4sRh3JAbJ5U5s7RfrWcctyD+TVRM="
    - # ^^ OSSRH_PASSWORD
    - secure: "rPG7QSazLqxPTyaZYZoPcoLRYv2mZxfL/zL31mPH9LBglPMigYhMbrhIJ2suCGksFOHoYlxgXAYPo2vvIxGKQ+1TMoVZkHKHryVPsRmtU6tTTj/Y00OjvyihaIHaQlcsJN8DxQOUEmEV9EuO3nGTRKp7H/cW97EPn62SAn+RbnXr2G7Cy396YLqJvcidmI2r2YPmE/vffoqw1amou76a6fftGW1uIQywtI+gFaZi7OX34fZgzFUadVbnsShLtrV4caceV8lu2cZZr72dc5SZD7s6peFX9Gy01jYkRU3FDpjNdQBftRaEz7f8vbaYVlilA90NRD2no43FfoyrQBvYEULQ2ziwLcrDKbcy1/SYViF1m5ulE1LfroG8iI0HdCfzfANaRrCi6ExevY8ypCk+xBkjsani5/Apv/B1AVhYvatt+MA4C6H7TAbJbR5+d7b9h3rqoj7QItb4bfpbO8SttejTQKq0cwsdMIKEozCXqWL7BmhGA+4GbLT7ER47cyyZR8653oXnvEy7eNMD15rXIcJqEKDM0oMxctU6xMJ9UGbOmF2yrPeCF8BA+hHuhytM1mb24NHfj4yL1tMC7RO61MfQ2C90Y+99XAsmz5map1rszzCf+ji2afzOiJH54PJxZTAI+pu8UA2RyN/aH+xodMLhTqKLfcdZB07sinKSUic="
    - # ^^ GPG_KEY_NAME
    - secure: "sdD5vUERbNEGtDYwkWjXAxvlkspbmxLB11y1N3v8hCyv42kJ7DQOlitTQGa29MS7cfemV6anImp9xXPgWwitqYHscw6fVAkIrHpvUEjOD/DqtkSLggDu/UbV/TSGb/CAg63KuT+tjAYEy/52fBoCxasOLV2Fm2vd1YrEml5KKNnccfh3l20G5dfx63Puiw8gAfreA4MO3vizP08pwYboC+hXYSu/lfW7+3jieVyvZTkz+y/6XOBnMFM0Tb+r0dzgEFmLxBSTeFmSG19uxNifqHKiCn2lN7ADAKCJFSzJH53G0tvvWykG4dX31v4tS9aJPwMmpz+7Bn+yguWCXPD+9UN9mubT3Gsgcz2ERU/xy8VI0Ji3qMwZ2cQxLyt+UOGkC5QA41PmrCs+3aTwvlgEZoJvcz7Sbqlo6XkLc/GIl57K4XVBZ8ykj7nvMoc0QBE1JJolg1N8NPaz8jBZuaNXvM/DLbAJXW8R32gON1a/zjxq9y141TSstDkZ+c7Gs/cVU1Wvyb+ipI9JJnoZck46AwGRhodxv5bX7JLr6mRQ3JncavPxllL8K1UXcxRB8MSS1PNOJLicNuZwrQ3UC0HmDBzcClMS9E+xGZwa6yM6lvquYnB3YFx7lPraqlILbOv2DUNB2zVlvvSzyB6Nb3gCWIIGGLJDfrAn4xAPjH7abJQ="
    - # ^^ GPG_PASSPHRASE
    - secure: "dqtfFomJCLnpjUYNvEeMH1JdJarvC6tjkDpRBTnLFTgF8aIPCKF8m3NQ9ipZuD3zdi8zVjMLvmSmXszLBabsqNqaqf5XTnn3LEmWQzC41Z7CMFsWxT7OT0hjFYDx9LsNjw+8o3YtmE/Jnlpd7gvpnx00RwC/z7OWpC4aVkrxMXVth7rnKRGqnvx6+P1JOezG2qVA3YSe1+snYFEgslmUWvbTccS8QTwmFayIR9aaozdQ8tVuc8zn1LjRMRxvKtzm0WKJASfmbYbGUNatzw4xle5DXmmhL+Q6J5041MmS7F2BYKsPKdQNCFUvnLxqKBAgfbuk4DZsYt+fgE/g167ysLz3N7B7uegmAKXOwEypwQe/HvmR4iqbqfqcrTconTxcrdQnGniENEJr5HkLqOvMqFwjKvNyIGxxgl8GfntZxVvxGddQItLdi81zXF0OpmxkDjxvST9iXfmsUN2iQhfhJMBI+XFYZ/6m1hHmMwrUTBc93zWujCUNft5s4Ou/b0MDjtt9r0bxqamYnfD+q5OC+oNhSzQZPJuvaEpL6E4/Si4J8ZuYjskuFKwkDSUMhB3XnarhhOHnCdA+kLm7kAziorPZB9VOX4x/x0LWggel4qv4JpEYQIj/Jrs5pZFKcQ8/MNFeqLHXJADiktpHQG6EW+wwykgZexznoqZ6rJ6WbLk="
before_install:
  - openssl aes-256-cbc -K $encrypted_29b97d90c267_key -iv $encrypted_29b97d90c267_iv -in codesigning.asc.enc -out codesigning.asc -d 
  - gpg --yes --batch --import codesigning.asc
jdk:
  - oraclejdk8
install: mvn --settings mvnsettings.xml clean install -P install -B -V -U
script:
- mvn deploy -P ossrh --settings mvnsettings.xml
cache:
  directories:
    - ~/.m2/repository
branches:
  only:
    - /^\d+\.\d+(\.\d+)?\/master$/
    - /^\d+\.\d+(\.\d+)?\/develop$/
notifications:
  email:
    on_success: change
    on_failure: change
