package com.merkle.oss.aem.utils.services.runmode.impl;

import com.merkle.oss.aem.utils.services.runmode.RunModeService;
import com.merkle.oss.aem.utils.services.runmode.modes.impl.EnvironmentTypeRunMode;
import com.merkle.oss.aem.utils.services.runmode.modes.impl.ServiceTypeRunMode;
import org.apache.commons.lang3.StringUtils;
import org.jspecify.annotations.NonNull;
import org.osgi.service.component.annotations.Activate;
import org.osgi.service.component.annotations.Component;
import org.osgi.service.metatype.annotations.AttributeDefinition;
import org.osgi.service.metatype.annotations.Designate;
import org.osgi.service.metatype.annotations.ObjectClassDefinition;
import org.osgi.service.metatype.annotations.Option;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.util.Collections;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;

/**
 * Component implementing the {@link RunModeService}.
 * <p>
 * This service manages the configuration for the AEM run mode identification logic,
 * retrieving settings defined via the OSGi Configuration console ({@code sling:OsgiConfig} files).
 */
@Component(service = RunModeService.class)
@Designate(ocd = RunModeServiceImpl.RunModeServiceConfig.class)
public class RunModeServiceImpl implements RunModeService {

    private static final Logger LOG = LoggerFactory.getLogger(RunModeServiceImpl.class);

    private boolean isAuthor;

    private EnvironmentTypeRunMode.Type environmenType;

    private Map<String, String> runModes;

    /**
     * Activates or modifies the service, retrieving the configuration parameters
     * from the OSGi Configuration.
     *
     * @param config The injected configuration object generated by the Metatype service.
     */
    @Activate
    protected void activate(@NonNull final RunModeServiceConfig config) {
        Objects.requireNonNull(config);
        runModes = new HashMap<>();

        if (!isConfigValid(config)) {
            LOG.error("Invalid configuration found for Run Mode Service. Configuration must be adjusted.");
            return;
        }

        if (ServiceTypeRunMode.Type.AUTHOR.is(config.serviceType())) {
            isAuthor = true;
            runModes.put(ServiceTypeRunMode.getKey(), ServiceTypeRunMode.Type.AUTHOR.getMode());
        } else {
            runModes.put(ServiceTypeRunMode.getKey(), ServiceTypeRunMode.Type.PUBLISH.getMode());
        }

        environmenType = EnvironmentTypeRunMode.Type.of(config.environmentType());
        runModes.put(EnvironmentTypeRunMode.getKey(), environmenType.getMode());
    }

    /**
     * Validates that the essential OSGi configuration properties are present.
     *
     * @param config The configuration to validate.
     * @return {@code true} if service type and environment type are non-blank.
     */
    private boolean isConfigValid(@NonNull final RunModeServiceConfig config) {
        return StringUtils.isNoneBlank(config.serviceType(), config.environmentType());
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public boolean isAuthor() {
        return isAuthor;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public boolean isPublish() {
        return !isAuthor;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public boolean isLocal() {
        return environmenType == EnvironmentTypeRunMode.Type.LOCAL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public boolean isRde() {
        return environmenType == EnvironmentTypeRunMode.Type.RDE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public boolean isDev() {
        return environmenType == EnvironmentTypeRunMode.Type.DEV;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public boolean isStage() {
        return environmenType == EnvironmentTypeRunMode.Type.STAGE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public boolean isProd() {
        return environmenType == EnvironmentTypeRunMode.Type.PROD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public @NonNull Map<String, String> getRunModes() {
        return Collections.unmodifiableMap(runModes);
    }

    /**
     * Defines the OSGi Metatype Configuration for the AEM Run Mode Service.
     * <p>
     * The properties defined here are used to identify the environment type.
     */
    @ObjectClassDefinition(name = "AEM Utils Run Mode Config", description = "Configures run modes for current instance and makes this information accessible for other services.")
    public @interface RunModeServiceConfig {

        /**
         * @return The primary service role of the AEM instance.
         */
        @AttributeDefinition(
                name = "Service Type",
                description = "Specifies if the instance behaves as an Author or Publish server.",
                options = {
                        @Option(value = ServiceTypeRunMode.MODE_TYPE_AUTHOR_VALUE, label = "Author"),
                        @Option(value = ServiceTypeRunMode.MODE_TYPE_PUBLISH_VALUE, label = "Publish"),
                })
        String serviceType() default "";

        /**
         * @return The environment tier the instance is currently running in.
         */
        @AttributeDefinition(
                name = "Environment Type",
                description = "Specifies the deployment tier (e.g., Development, Staging, Production).",
                options = {
                        @Option(value = EnvironmentTypeRunMode.MODE_ENV_LOCAL_VALUE, label = "local"),
                        @Option(value = EnvironmentTypeRunMode.MODE_ENV_RDE_VALUE, label = "rde"),
                        @Option(value = EnvironmentTypeRunMode.MODE_ENV_DEV_VALUE, label = "dev"),
                        @Option(value = EnvironmentTypeRunMode.MODE_ENV_STAGE_VALUE, label = "stage"),
                        @Option(value = EnvironmentTypeRunMode.MODE_ENV_PROD_VALUE, label = "prod"),
                })
        String environmentType() default "local";

    }

}
